name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr
        remote_path: /var/www/html/development/github_action_test/
        remote_host: 110.44.116.54
        remote_user: ubuntu
        remote_password: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
